### ISSUE TITLE
GitHub & Cloud Storage (e.g. Dropbox)

### ISSUE THREAD

**Issue by w4rner** [macss-uml19/Problem-Set-1#1]
Following on from today's conversation,
This article, on the potential problems: https://www.anishathalye.com/2015/08/19/git-remote-dropbox/.

Seems Prof Waggoner's been fortunate to avoid. I'm gonna avoid mixing them myself, but if folks want to take precautions:
1). https://stackoverflow.com/questions/1960799/using-git-and-dropbox-together-effectively

2). Medium article:
https://blog.geekforbrains.com/how-to-use-dropbox-and-git-for-private-repos-e1d304d5ff79

**Comment by pdwaggoner** [comment]
Many thanks @w4rner  - super helpful to consider.
